"use client";


import { useState } from "react";
import { format } from "sql-formatter";
import { CopyButton } from "@/components/CopyButton";

export default function SqlFormatterPage() {
  const [input, setInput] = useState("");
  const [output, setOutput] = useState("");
  const [error, setError] = useState("");
  const [lang, setLang] = useState<"sql" | "mysql" | "postgresql">("sql");

  const fmt = () => {
    try {
      setOutput(format(input, { language: lang }));
      setError("");
    } catch (e: unknown) { setError((e as Error).message); }
  };

  return (
    <div className="tool-page">
      <h1>SQL Formatter</h1>
      <p className="desc">Format and beautify SQL queries.</p>
      <div className="btn-group items-center">
        <label>Dialect:</label>
        <select value={lang} onChange={(e) => setLang(e.target.value as typeof lang)}>
          <option value="sql">Standard SQL</option>
          <option value="mysql">MySQL</option>
          <option value="postgresql">PostgreSQL</option>
        </select>
      </div>
      <textarea className="tool-input" value={input} onChange={(e) => setInput(e.target.value)} placeholder="SELECT * FROM users WHERE id = 1" />
      <div className="btn-group">
        <button className="btn btn-primary" onClick={fmt}>Format</button>
        <button className="btn" onClick={() => { setInput(""); setOutput(""); setError(""); }}>Clear</button>
        <CopyButton text={output} />
      </div>
      {error && <p className="error-text">❌ {error}</p>}
      {output && <div className="output-box">{output}</div>}

      <section className="tool-prose">
        <h2>About the SQL Formatter</h2>
        <p>The SQL Formatter beautifies and standardizes SQL query syntax for improved readability. Paste any SQL statement — SELECT, INSERT, UPDATE, DELETE, CREATE TABLE, or complex multi-join queries — and get properly indented, keyword-capitalized output instantly.</p>
        <p>Well-formatted SQL is easier to read, review, and debug. Inconsistent indentation and random capitalization are common in SQL generated by ORMs, query builders, or copy-pasted from Stack Overflow. Standardizing formatting makes it easier to spot logical errors, understand join conditions, and perform code review.</p>
        <p>This tool uses the sql-formatter library. All formatting runs locally in your browser — no SQL queries are sent to any server, making it safe to format queries containing table names, column names, or filter values from production databases.</p>
      </section>
    </div>
  );
}
